apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secret-store-vault # 指向刚才创建的 secretStore CRD
    kind: ClusterSecretStore
  target:
    name: my-secret # K8S secret 名称
  data:
    - secretKey: MY_PASSWORD # K8S secret key in the secret
      remoteRef:
        key: k8s/example # vault secret path
        property: PASSWORD # vault secret key
