apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store-vault
spec:
  provider:
    vault:
      server: "https://mwplat-vault.homecreditcfc.cn"
      version: "v2"
      path: "Test"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "hvs.GIHnn7IUVysIHBxAA5DSBPHC"
