apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: github-pipeline-ex3
spec:
  taskRunSpecs:
    - pipelineTaskName: git-clone
      serviceAccountName: build-bot
  pipelineRef:
    name: github-pipeline-ex3
  params:
    - name: git_url
      value: "https://github.com/devops-advanced-camp/vote.git"
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: pipeline-pvc
      subPath: $(context.pipelineRun.uid)
    - name: sonar-credentials
      secret:
        secretName: sonar-user-pass
    - name: docker-credentials
      secret:
        secretName: docker-credentials
