apiVersion: v1
kind: Secret
metadata:
  name: sonar-user-pass
type: Opaque
stringData:
  login: "squ_0f066238b493d943c1b7c04e5e1dafdd1d4d18ed"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonar-user-pass
secrets:
  - name: sonar-user-pass
