apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers
  triggers:
    - name: github-push-events-trigger-result
      interceptors:
        - ref:
            name: github
          params:
            # - name: secretRef
            #   value:
            #     secretName: github-secret
            #     secretKey: secretToken
            - name: "eventTypes"
              value:
                - pull_request
                - push
            - name: "addChangedFiles"
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              # execute only when a file within the controllers directory has changed
              value: extensions.changed_files.matches('result/')
      bindings:
        - name: git_url
          value: $(body.repository.clone_url)
        - name: commit_id
          value: $(body.after)
        - name: microservice
          value: "result"
      template:
        ref: github-template

    - name: github-push-events-trigger-vote
      interceptors:
        - ref:
            name: github
          params:
            # - name: secretRef
            #   value:
            #     secretName: github-secret
            #     secretKey: secretToken
            - name: "eventTypes"
              value:
                - pull_request
                - push
            - name: "addChangedFiles"
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              # execute only when a file within the controllers directory has changed
              value: extensions.changed_files.matches('vote/')
      bindings:
        - name: git_url
          value: $(body.repository.clone_url)
        - name: commit_id
          value: $(body.after)
        - name: microservice
          value: "vote"
      template:
        ref: github-template

    - name: github-push-events-trigger-worker
      interceptors:
        - ref:
            name: github
          params:
            # - name: secretRef
            #   value:
            #     secretName: github-secret
            #     secretKey: secretToken
            - name: "eventTypes"
              value:
                - pull_request
                - push
            - name: "addChangedFiles"
              value:
                enabled: true
        - ref:
            name: cel
          params:
            - name: filter
              # execute only when a file within the controllers directory has changed
              value: extensions.changed_files.matches('worker/')
      bindings:
        - name: git_url
          value: $(body.repository.clone_url)
        - name: commit_id
          value: $(body.after)
        - name: microservice
          value: "worker"
      template:
        ref: github-template
