apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgA6ZdfGQyTizdtqR+2v9ZNHpR0lYAsYJGXtnhx6+veS43jROlO9IPKryWun7rXKcsxGdi1pltBSP6swo4CIcvrQpnD0W4vhNNZV1NZJyYHBdzHSuI3Vs9OVJAbwWd77PQWqmbuiuskTvjdH2n7xdJb7X4pv+6pXH5cVL+jm8UYYQq9AuEIBnvsz/pme6tk7MjgPQInah6x5kvHQst6R948hVdNw1Sw35pJJ1Vty9Iq+L0EjB78qmoeMSTB9MjFmArW+B5JUarfmhu6KUAfFwm3fHZDeHjsx06tjSbZD7fY+Waj20xFQwfoMIX8zuU6L8ENYahf5VCLwzY2Gz0b0PAKVsqgrZwqS0Gt2rVrJCRQZaQAPRE/un3dojN+Ix/v4v2/cn2ELyzF55YlZfbdn/GQNuHOVQY8UwMqK7SgLAZoMT5tYxx3p7TTQZCVTn8HIA40O1zn+95vkkR00YSEhAHrTycKuOpJUh5Rp/gwX9b4likk13vpt/es5yQH8WjAuP2PeHuq0t9wHJDcuoOOcls+oyLt184HYOvO82pZ0858j3srB5DXE+wwr3NhGWvDam6iL+waXdnTDB98AL0UCiSbtMEBVSt3a+8opXXVZn701SKyBDi6rUlPFwSi86C/feLRGAO67sb1qUM+fPI7/HgvKwD3Z6hg+4QknCCU8uUmOlw2iIF1XfehifWtoGNDFBjgqk/8W32oe6/LH5TZ5D5E5caUAzNmFjq/S+nnZ734ymtne+HRXh986RR5vVDpS5+XO8o1k8gq8kyfpWGFk1o/g9I+8JGrLKsA2GCRUb7w4+dAyNO1zeO0/xRo/UBi9mM7UvZKZrEYqjD/d5F69firHpxytW9hr8M3ChplEW5dYr1xHB1esjayYSTYbjvnGS0yPeD5qAdMjMKCQxvDBB0vgRsfDCBa28tQl5UglkU9DYJg3xTPWvBb/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
---
