apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-secret
  namespace: default
spec:
  encryptedData:
    password: AgAcJrgx24GsrH+PMZPPY/lqz0DUjdvBWHGh6nlky/HYrv94dCSwqw0qiuf+xmAJRWZ5XOkqhcbKAlgicuWoUcz2hUFWKjGtSvYlV4xC8XgkbeHnQJo/BLfDh/PHR0tVsUUQQ0cxzyLgQlZzUD9lhbgDUMrbADVlMUh/tj9Ek5bS1Qg0gERruBOrPMpFt/Myj8jOcCatn8AfMRHQciXDqbsPG2+Bpnqt72SMX5FQPt3XmFKgLGcJEpJkAIRg7HzRn2Pp7L3a17BkxezUR75BxVFKSUSuX1z+P3L4LkUDXs/s+f1BVPhpB3G7UUzPyXFT+j3SCwML32Z8DyPZS+0D2RBM3wyKJjDkf5o5vdDbazSkMlURbRWfvB7zL8v7Pv5PC0K0m35V8yAmC7zW2P4Rwcv6ER0xQIIgEbChbuhYp76ZmZXRBFRhby7wAQYGeVSN4yNx+TtdreN08mmHP+8Hu8NGWXn9uA9VjLs5ZztbIHXEXb1f3Be93MBs1uU40eRE4kLYcdVRYEBdU9/5PROd1mDlPK3SSBGnFuQkqENrTkhUX+wACIfg4ovvol70W5MrvSco9oRMtRUzW6XfOBfheOKCQui9AUu6oLDDXWVxstlQ4Wp+Kn87IxeDzL78cko0OzZpsC8Pc/12y4UcpOou6o0n0jclMGDAXBYASe3ZZlWwD2SfvYOhn4XRTe/KfiJictPb0sEEPVi6VdgFXQ==
    username: AgBoO8f+lS2n0B02dov1b0O1CcidNXzIiamaLoOmCCmtrNVdgxy53Xhb20zSmgRDP1ccWX3T/JQRZyvS9jM74Nqu6/sFXRaxh8l7IFZyRFXrV61ySwiBgwVg8zElUrXBaMM8Qo++ZYgtMNlaMgZbWYEC+MXqYRC3lTUYLBX0rixxWwzV3cgxpN/4swaKnMd20gKD+xeoZMu6ywSEKHE0OZ5liCeiuIcOmPy7BBGxoaBcyMcm9LlKqmP8h/NnhsxnBq0pKA+dQ/Cbur2W9mT7UnLzuckCyxQKPPvLvcl1/iBzkjjFzOX7DrlIaVSzatY4olEkChHcWB/VDZ2Uj18eDF5DFNeQt15aZHzic3m3o/6Y+egysMYP8ec8exmC7fgqpO2wPPqmscKM+3xKTk6NJGUFPbNz4MQcunni0cXNiIqfKy09flF3TGqHFs3CxzKqGSp82ChPtD5H0hmURHOFUWJIuOr24QLAB5TzzNs9MrsYny8ksfDzBwD9CayLXumhgDEjbClFV0EbIn0qnen8/W4xgobstKF0tgd3izFWOcsyVnEd7MbBAR2fM59x5L7WECgi7YkjvNKEHWWWjJs9g/pqx7F84NVX7fZ/A6cg1zI+w6MiBROk62mooY7MjP9OumItWIenmecVDQxIWvVGV3Uf6whmVEjgOq/m94G+nn2PvBjQl8CkHvb5156ipGNip01CDiomSQ==
  template:
    metadata:
      creationTimestamp: null
      name: example-secret
      namespace: default
---
